#!/bin/sh
#
# Example on how to start the ArchiveEngine
#
# kasemir@lanl.gov

# On a distributed system,
# you can access all the archive files from many machines,
# but you want to assert that the ArchiveEngine runs
# only on a specific host and not accidentally on another one:
if [ `hostname` != gopher0 ]
then
    echo "You are not on the machine where this ArchiveEngine"
    echo "is supposed to run"
    exit
fi

# Rename an existing log file in case we want to look
# at it later
if [-f log]
then
    mv log log`date +%y%m%d%H%M%S`
fi

# Start engine:
# -put data in some subdirectory
# -use specific port for HTTP interface
# -copy output to "log" file
ArchiveEngine main.cfg 06_01/dir -d "Master Archive" -p 4819 -l log &

