#	Makefile.Host

include ../../Make.cfg
include ../../Make.ver

CXXFLAGS += -DMANAGER_VERSION=\"$(VERSION).$(RELEASE)\"

SRCS += ascii.cc
SRCS += main.cc

PROD := ArchiveManager

include ../../Make.end
