#	Makefile.Host

include ../../Make.cfg
include ../../Make.ver

CXXFLAGS += -DCGIEXPORT_VERSION=\"$(VERSION).$(RELEASE)\"

SRCS += CGIInput.cc
SRCS += HTMLPage.cc
SRCS += main.cc

PROD := CGIExport

include ../../Make.end
