# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded atacTools 1.0 [list tclPkgSetup $dir atacTools 1.0 {{atacTools.tcl source {TimeLabelCommand addGraphData addToGraph createAtacGraph formatValue initGraphData saveGraph secs2stamp stamp2secs stamp2values stampNow values2stamp}}}]
